services:
  database:
    image: mongo:8.2
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - private

  backend:
    build:
      context: .
      dockerfile: dockerfile
      target: dev
    ports:
      - '3000:3000'
    networks:
      - private
    depends_on:
      - database

volumes:
  mongo_data:

networks:
  private:
    driver: bridge
